Vagrant.configure("2") do |config|

    config.vm.provision "shell", inline: <<-SHELL
      echo "10.0.0.11 control-node-01" >> /etc/hosts
      echo "10.0.0.21 worker-node-01" >> /etc/hosts
      echo "10.0.0.22 worker-node-02" >> /etc/hosts
      echo "10.0.0.23 worker-node-03" >> /etc/hosts
    SHELL
    
    (1..1).each do |i|
      config.vm.define "control-node-0#{i}" do |control|
        control.vm.box = "generic/oracle7"
        control.vm.box_check_update = true
        control.vm.hostname = "control-node-0#{i}"
        control.vm.network "private_network", ip: "10.0.0.1#{i}"
        control.disksize.size = "200GB"
        control.vm.provider "virtualbox" do |vb|
          vb.name = "vanilla-kubernetes-cluster-oraclelinux7-control-node-0#{i}"
          vb.memory = 4048
          vb.cpus = 2
        end
        control.vm.synced_folder "../shared", "/vagrant"
        control.vm.provision "shell", path: "../shared/scripts/common-utils-oraclelinux7.sh"
        control.vm.provision "shell", path: "../shared/scripts/control-node.sh"
      end
    end

    (1..3).each do |i|
      config.vm.define "worker-node-0#{i}" do |node|
        node.vm.box = "generic/oracle7"
        node.vm.box_check_update = true
        node.vm.hostname = "worker-node-0#{i}"
        node.vm.network "private_network", ip: "10.0.0.2#{i}"
        node.disksize.size = "200GB"
        node.vm.provider "virtualbox" do |vb|
          vb.name = "vanilla-kubernetes-cluster-oraclelinux7-worker-node-0#{i}"
          vb.memory = 4048
          vb.cpus = 2
        end
        node.vm.synced_folder "../shared", "/vagrant"
        node.vm.provision "shell", path: "../shared/scripts/common-utils-ubuntu.sh"
        node.vm.provision "shell", path: "../shared/scripts/worker-node.sh"
      end
    end

  end